name: Container Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [backend, frontend]
    steps:
    - uses: actions/checkout@v2
    - name: Login to github docker Registry
      run: docker login docker.pkg.github.com -u iamangus -p ${{ secrets.GITHUB_TOKEN }}
    - name: Set Date based var for use in tag
      id: vars
      run: echo ::set-output name=tag::$(echo $(date +%s))
    - name: Build the tagged Docker image
      run: docker build ./${{ matrix.service }} --file ./${{ matrix.service }}/Dockerfile --tag docker.pkg.github.com/iamangus/omniarr/${{ matrix.service }}:latest
    - name: Push the latest Docker image
      run: docker push docker.pkg.github.com/iamangus/omniarr/${{ matrix.service }}:latest
    - name: retag and push
      run: docker tag docker.pkg.github.com/iamangus/omniarr/${{ matrix.service }}:latest docker.pkg.github.com/iamangus/omniarr/${{ matrix.service }}:${{steps.vars.outputs.tag}}
    - name: Push the tagged Docker image
      run: docker push docker.pkg.github.com/iamangus/omniarr/${{ matrix.service }}:${{steps.vars.outputs.tag}}